modLoader="javafml"
loaderVersion="[34,)"
license="GPL v3.0"
issueTrackerURL="https://github.com/PieKing1215/StartupQoL/issues"
[[mods]]
modId="startupqol"
version="0.3.0"
displayName="Startup QoL"
displayURL="https://github.com/PieKing1215/StartupQoL"
logoFile="logo.png"
#credits=""
authors="PieKing1215"
description='''
Adds some quality of life features related to game startup.'''

[[dependencies.startupqol]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.startupqol]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.16.4,1.16.5]"
    ordering="NONE"
    side="BOTH"