modLoader="javafml"
loaderVersion="[34,)"
license="GPL v3.0"
issueTrackerURL="https://github.com/PieKing1215/StartupQoL/issues"
[[mods]]
modId="startupqol"
version="0.1.2"
displayName="Startup QoL"
displayURL="https://github.com/PieKing1215/StartupQoL"
logoFile="logo.png"
#credits=""
authors="PieKing1215"
description='''
Prevents the game from going fullscreen until the main menu.
Also shows the total startup time on the main menu.'''

[[dependencies.startupqol]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.startupqol]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"