modLoader="javafml"
loaderVersion="[31,)"
license="GPL v3.0"
issueTrackerURL="https://github.com/PieKing1215/StartupQoL/issues"
[[mods]]
modId="startupqol"
version="0.2.0"
displayName="Startup QoL"
displayURL="https://github.com/PieKing1215/StartupQoL"
logoFile="logo.png"
#credits=""
authors="PieKing1215"
description='''
Adds some quality of life features related to game startup.'''

[[dependencies.startupqol]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.startupqol]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"